# Generated by Django 2.2.8 on 2020-02-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a test description muy bien productos!!'),
            preserve_default=False,
        ),
    ]
